apiVersion: v1
kind: Service
metadata:
  name: netology-svc-dep
  namespace: netology  
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
    - name: mtool
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx-multitool
      