apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-nginx
  labels:
    app: app
  namespace: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: v2
  template:
    metadata:
      labels:
        app: app
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
          - containerPort: 80
        volumeMounts:
          - name: config-two
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: config-two
        configMap:
          name: config-two
---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: netology  
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app  
    version: v2       