apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config 
  namespace: {{ .Values.namespace.name }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Страница из ConfigMap</title> 
      <meta charset="UTF-8">
    </head>
    <body>
      <h1>Привет от Kubernetes! namespace is {{ .Values.namespace.name }}</h1> 
      <h1>Version nginx is {{ .Values.image.tag }}</h1> 
    </body>
    </html>